CREATE TABLE CAR(ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,NAME VARCHAR(255),TYPE_ID BIGINT,COLOR VARCHAR(255),PRICE DECIMAL(18, 2),AMOUNT INT);

CREATE TABLE CAR_TYPE (ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY,NAME VARCHAR(255) NOT NULL);

ALTER TABLE CAR ADD CONSTRAINT CAR_FK FOREIGN KEY (TYPE_ID) REFERENCES CAR_TYPE(ID);

INSERT INTO CAR_TYPE (ID, NAME) VALUES(1, 'SEDAN');
INSERT INTO CAR_TYPE (ID, NAME) VALUES(2, 'COUPE');
INSERT INTO CAR_TYPE (ID, NAME) VALUES(3, 'HATCHBACK');
INSERT INTO CAR_TYPE (ID, NAME) VALUES(4, 'OTHER');
INSERT INTO CAR_TYPE (ID, NAME) VALUES(5, 'TRUCK');
INSERT INTO CAR_TYPE (ID, NAME) VALUES(6, 'TANK');
INSERT INTO CAR_TYPE (ID, NAME) VALUES(7, 'SPORTS CAR');

INSERT INTO CAR (ID, NAME, COLOR, PRICE, AMOUNT, TYPE_ID) VALUES(1, 'Lightning McQueen', 'RED', 1.00, 1, 7);
INSERT INTO CAR (ID, NAME, COLOR, PRICE, AMOUNT, TYPE_ID) VALUES(2, 'Optimus Prime', 'RED+BLUE', 2.00, 0, 5);
INSERT INTO CAR (ID, NAME, COLOR, PRICE, AMOUNT, TYPE_ID) VALUES(4, 'The Flintstones Flintmobile', '?', 4.0, 3, 4);
INSERT INTO CAR (ID, NAME, COLOR, PRICE, AMOUNT, TYPE_ID) VALUES(3, 'The Batmobile', 'BLACK', 3.00, 2, 6);
